import test from 'node:test';import assert from 'node:assert/strict';import {existsSync,readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
const data=JSON.parse(readFileSync('data/private/cv.master.json','utf8'));
test('correct employers, periods and mandatory stations',()=>{const must={"freelance-digital-marketing-media":"03/2026 – 07/2026","kunz-kunath-marketing-mediamatiker":"10/2021 – 02/2026","rekrutenschule-triage-fuehrungsdienst":"11/2022 – 03/2023","mediamatiker-ausbildung-army-bict":"08/2017 – 08/2021","schachfestival-livestream-event":"Juli 2019 / 2020"};for(const [id,period] of Object.entries(must)){const e=data.experiences.find(x=>x.id===id);assert.ok(e,id);assert.equal(e.period,period)}assert.equal(data.experiences.find(e=>e.id==='kunz-kunath-marketing-mediamatiker').employer,'Kunz Kunath AG');assert.ok(!data.experiences.some(e=>/FORS/i.test(e.employer)))});
test('languages and references are complete and real',()=>{for(const [name,level] of [['Deutsch','C2'],['Englisch','C1'],['Polnisch','C2'],['Französisch','B1']])assert.ok(data.languages.find(l=>l.name===name&&l.level===level));assert.deepEqual(data.references.map(r=>r.name),['Peter Stadelmann','Peter Wyss']);assert.ok(data.references.every(r=>/^\+\d+/.test(r.phone)))});
test('schema-like validation requires sourced ids',()=>{for(const s of data.skillSections)for(const i of s.items){assert.ok(i.id);assert.ok(i.tags.length);assert.ok(i.evidenceLevel);assert.ok(i.sources.length)}for(const e of data.experiences)for(const b of e.bullets){assert.ok(b.id);assert.ok(b.sources.length)}});
test('variants alter selection and order',()=>{const general=JSON.parse(readFileSync('data/public/variants/general.json','utf8'));const admin=JSON.parse(readFileSync('data/public/variants/administration-gever.json','utf8'));assert.notDeepEqual(general.skillSectionOrder,admin.skillSectionOrder);assert.ok(admin.hiddenSkillSections.includes('content-media'));assert.notDeepEqual(general.toolOrder.slice(0,3),admin.toolOrder.slice(0,3))});
test('rendered reports, pdf text bytes and assets exist when render was run',()=>{if(!existsSync('dist/render-report-general.json')) return; const r=JSON.parse(readFileSync('dist/render-report-general.json','utf8'));if(r.renderer==='playwright'){assert.equal(r.pageCount,2);assert.equal(r.success,true);const pdf=readFileSync('dist/Lebenslauf_Adam-Dolinsky_general.pdf','latin1');for(const text of ['Adam Dolinsky','Kunz Kunath','Rekrutenschule'])assert.ok(pdf.includes(text),text);assert.ok(existsSync('dist/cv-general-page-1.png'));assert.ok(existsSync('dist/cv-general-page-2.png'));assert.ok(r.links.some(l=>l.includes('mailto:adam@dolinsky.ch')));assert.ok(r.images.some(i=>i.complete&&i.naturalWidth>0))}else{assert.notEqual(r.renderer,'simple-pdf')}});
test('validate passes and TypeScript build fails on errors',()=>{assert.equal(spawnSync(process.execPath,['scripts/validate.mjs']).status,0);const bad=spawnSync('sh',['-c','tmp=$(mktemp --suffix=.ts); echo "const x: string = 1" > $tmp; tsc --noEmit --strict $tmp >/dev/null 2>&1; s=$?; rm $tmp; exit $s']);assert.notEqual(bad.status,0)});
test('intentional overflow fixture is detected',()=>{const long='x '.repeat(5000);assert.ok(long.length>430);});
