import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
import { normalizeAtsText, joinPdfTextItems } from '../src/lib/ats-normalize.mjs';
const dataText=readFileSync('data/private/cv.master.json','utf8');const publicText=readFileSync('data/public/cv.master.example.json','utf8');const data=JSON.parse(dataText);
test('correct employers, periods and mandatory stations',()=>{const must={"freelance-digital-marketing-media":"03/2026 – heute","kunz-kunath-marketing-mediamatiker":"10/2021 – 02/2026","rekrutenschule-triage-fuehrungsdienst":"11/2022 – 03/2023","mediamatiker-ausbildung-army-bict":"08/2017 – 08/2021","schachfestival-livestream-event":"Juli 2019 / 2020"};for(const [id,period] of Object.entries(must)){const e=data.experiences.find(x=>x.id===id);assert.ok(e,id);assert.equal(e.period,period)}assert.equal(data.experiences.find(e=>e.id==='kunz-kunath-marketing-mediamatiker').employer,'Kunz Kunath AG');assert.ok(!data.experiences.some(e=>/FORS/i.test(e.employer)))});
test('freelance location uses sourced Neukaledonien wording and never France',()=>{assert.equal(dataText.includes('Frankreich'),false);const e=data.experiences.find(x=>x.id==='freelance-digital-marketing-media');assert.ok(e.employer.includes('Neukaledonien'));assert.ok(e.employer.includes('ab 06/2026 in Bern'));assert.equal(e.location,'Neukaledonien / Bern')});
test('Kunz Kunath contains sourced Onlineshop content bullet and no monitoring wording',()=>{const flat=JSON.stringify(data);assert.ok(flat.includes('Onlineshop-Management inkl. Content-, Struktur- und Produktpflege'));assert.equal(flat.includes('Onlinekampagnen inkl. Monitoring und Erfolgskontrolle'),false)});
test('workload text is exact',()=>{assert.equal(data.workload.text,'60–100 % flexibel nach Absprache')});
test('languages and references are complete and real',()=>{assert.deepEqual(data.languages.map(l=>l.name),['Deutsch','Englisch','Französisch','Polnisch']);for(const [name,level] of [['Deutsch','C2'],['Englisch','C1'],['Französisch','B1'],['Polnisch','C2']])assert.ok(data.languages.find(l=>l.name===name&&l.level===level));assert.deepEqual(data.references.map(r=>r.name),['Peter Stadelmann','Peter Wyss']);assert.ok(data.references.every(r=>/^\+\d+/.test(r.phone)));const wyss=data.references.find(r=>r.name==='Peter Wyss');assert.equal(wyss.phone,'+41 58 489 20 03');assert.equal('manualVerificationRequired' in wyss,false);assert.equal(dataText.includes('+51 58 489 20 03'),false);assert.equal(publicText.includes('+51 58 489 20 03'),false)});
test('schema-like validation requires sourced ids',()=>{for(const s of data.skillSections)for(const i of s.items){assert.ok(i.id);assert.ok(i.tags.length);assert.ok(i.evidenceLevel);assert.ok(i.sources.length)}for(const e of data.experiences)for(const b of e.bullets){assert.ok(b.id);assert.ok(b.sources.length)}});
test('variants alter selection and order',()=>{const general=JSON.parse(readFileSync('data/public/variants/general.json','utf8'));const admin=JSON.parse(readFileSync('data/public/variants/administration-gever.json','utf8'));assert.notDeepEqual(general.skillSectionOrder,admin.skillSectionOrder);assert.ok(admin.hiddenSkillSections.includes('content-media'));assert.notDeepEqual(general.toolOrder.slice(0,3),admin.toolOrder.slice(0,3));assert.equal(general.maxBulletsPerExperience,7);assert.ok(general.selectedBulletIds.includes('bullet-freelance-french'));assert.ok(general.selectedBulletIds.includes('bullet-freelance-self-organization'))});
test('workflow avoids npm ci/cache npm without lockfile and uses Node 22',()=>{const wf=readFileSync('.github/workflows/render-cv.yml','utf8');assert.equal(wf.includes('npm ci'),false);assert.equal(wf.includes('cache: npm'),false);assert.equal(wf.includes('push:'),false);assert.ok(wf.includes('node-version: 22'));assert.ok(wf.includes('npm install --no-audit --no-fund'))});
test('validate passes and TypeScript build fails on errors',()=>{assert.equal(spawnSync(process.execPath,['scripts/validate.mjs']).status,0);const bad=spawnSync('sh',['-c','tmp=$(mktemp --suffix=.ts); echo "const x: string = 1" > $tmp; tsc --noEmit --strict $tmp >/dev/null 2>&1; s=$?; rm $tmp; exit $s']);assert.notEqual(bad.status,0)});

test('optional and supplementary content is verified and variant-bound',()=>{assert.ok(data.supplementaryIndicators?.tools?.enabled);const optional=data.experiences.flatMap(e=>(e.optionalBullets||[]).map(b=>({...b,experienceId:e.id})));assert.ok(optional.length>=4);for(const b of optional){assert.ok(b.id.startsWith('optional-'));assert.ok(b.text);assert.ok(b.shortText);assert.ok(b.tags.length);assert.ok(b.evidenceLevel);assert.ok(b.sources.length);assert.ok(b.variantRelevance.length);assert.ok(Number.isInteger(b.fillPriority));assert.ok(b.preferredMaxChars>0);assert.ok(['verified','defensible_inference','inferred_review_required'].includes(b.status));assert.ok(Array.isArray(b.atsSynonyms))}const training=data.experiences.find(e=>e.id==='mediamatiker-ausbildung-army-bict');assert.ok(training.optionalBullets.some(b=>/Web|digitale Medien|Dokumentation|Projektarbeit/.test(b.text)));const event=data.experiences.find(e=>e.id==='schachfestival-livestream-event');assert.ok(event.optionalBullets.some(b=>/Livestreaming|Eventorganisation|Veranstaltungsbetrieb/.test(b.text))) });


test('page.evaluate transfers one serializable payload object',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('page.evaluate(({ bgExists, variantMeta }) =>'));assert.ok(src.includes('bgExists: backgroundFileExists'));assert.equal(src.includes('}, backgroundFileExists, {'),false)});

test('tool pool includes only sourced tool records with visibility metadata',()=>{assert.ok(data.tools.length>11);for(const tool of data.tools){assert.ok(tool.id.startsWith('tool-'));assert.ok(tool.name);assert.ok(tool.tags.length);assert.ok(tool.evidenceLevel);assert.ok(tool.sources.length);assert.equal(typeof tool.surfaceAutomatically,'boolean');assert.ok(Array.isArray(tool.allowedVariants));assert.ok(Number.isInteger(tool.priority));assert.ok(tool.category);assert.ok(Array.isArray(tool.atsSynonyms));assert.ok(['verified','defensible_inference','inferred_review_required'].includes(tool.status))}assert.ok(data.tools.find(t=>t.id==='tool-adobe-indesign'&&t.surfaceAutomatically===false));assert.ok(data.tools.find(t=>t.id==='tool-adobe-photoshop'&&t.surfaceAutomatically===false))});


test('fill gap uses visible experience content bottom instead of flex container bottom',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('getExperienceContentBottom'));assert.ok(src.includes("#experience-list .experience:not([hidden])"));assert.equal(src.includes('bottomGrid.top - experienceList.bottom'),false)});


test('adaptive fill uses preferred and max counts instead of hard optionalBulletLimit',()=>{for(const name of ['general','communication-content','administration-gever','cms-web-process']){const v=JSON.parse(readFileSync(`data/public/variants/${name}.json`,'utf8'));assert.equal('optionalBulletLimit' in v.fill,false);assert.ok(v.fill.preferredOptionalBulletCount>=0);assert.ok(v.fill.maxOptionalBullets>=v.fill.preferredOptionalBulletCount)}});

test('administration variant includes ATS-friendly administrative source blocks',()=>{const admin=JSON.parse(readFileSync('data/public/variants/administration-gever.json','utf8'));for(const id of ['bullet-rs-acta-nova','bullet-rs-quality','bullet-rs-doc-management','bullet-rs-coordination','bullet-kunz-process-handover'])assert.ok(admin.selectedBulletIds.includes(id));const flat=JSON.stringify(data);for(const term of ['Digitale Geschäftsvorgangsbearbeitung','Dokumentenmanagement','Qualitätsprüfung','formale Kontrolle','Prozessdokumentation','Wissenssicherung'])assert.ok(flat.includes(term),term)});


test('ATS normalization is case-insensitive and robust against PDF line breaks',()=>{assert.equal(normalizeAtsText('ADAM DOLINSKY'),normalizeAtsText('Adam Dolinsky'));assert.equal(normalizeAtsText('Digital Marketing · Web · Content · KI-\ngestützte Prozesse'),normalizeAtsText('Digital Marketing · Web · Content · KI-gestützte Prozesse'));assert.equal(normalizeAtsText('MS Office'),normalizeAtsText('MS Office'));assert.equal(normalizeAtsText('Kunz   Kunath AG'),normalizeAtsText('Kunz Kunath AG'))});

test('ATS normalization does not fuzzy-match absent terms',()=>{const pdfText=normalizeAtsText('ADAM DOLINSKY Digital Marketing · Web · Content · KI-\ngestützte Prozesse MS Office Kunz   Kunath AG');assert.equal(pdfText.includes(normalizeAtsText('Nicht vorhandener Begriff')),false)});


test('PDF.js hasEOL item joining preserves hyphenated line breaks for ATS matching',()=>{const items=[{str:'Digital Marketing · Web · Content · KI-',hasEOL:true},{str:'gestützte Prozesse',hasEOL:false}];const extracted=joinPdfTextItems(items);assert.equal(normalizeAtsText(extracted),normalizeAtsText('Digital Marketing · Web · Content · KI-gestützte Prozesse'))});

test('PDF.js item joining does not collapse legitimate hyphen-space wording',()=>{const items=[{str:'Newsletter-Konzeption und Umsetzung (Print- und E-Mail)',hasEOL:false}];const extracted=joinPdfTextItems(items);assert.equal(extracted,'Newsletter-Konzeption und Umsetzung (Print- und E-Mail)');assert.equal(normalizeAtsText(extracted),normalizeAtsText('Newsletter-Konzeption und Umsetzung (Print- und E-Mail)'));assert.equal(normalizeAtsText(extracted).includes('print-und e-mail'),false)});


test('each variant has at least fourteen sourced visible tools',()=>{const master=new Map(data.tools.map(t=>[t.id,t]));for(const name of ['general','communication-content','administration-gever','cms-web-process']){const v=JSON.parse(readFileSync(`data/public/variants/${name}.json`,'utf8'));const ids=v.toolOrder.slice(0,v.maxTools);assert.ok(ids.length>=14,`${name} tool count`);assert.equal(new Set(ids).size,ids.length,`${name} unique tools`);for(const id of ids){const tool=master.get(id);assert.ok(tool,`${id} in master`);assert.ok(tool.sources?.length,`${id} sourced`);assert.notEqual(tool.status,'inferred_review_required',`${id} not review-only`)}}});

test('visible experience bullet fallback content is source-backed and safe',()=>{const rs=data.experiences.find(e=>e.id==='rekrutenschule-triage-fuehrungsdienst');for(const id of ['bullet-rs-admin-support-summary','bullet-rs-digital-information-summary']){const bullet=rs.bullets.find(b=>b.id===id);assert.ok(bullet,id);assert.ok(['verified','defensible_inference'].includes(bullet.status));assert.ok(bullet.sources?.length);assert.ok(bullet.sourceIds?.length);assert.ok(bullet.inferenceRationale)}});
