import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
import { normalizeAtsText, joinPdfTextItems } from '../src/lib/ats-normalize.mjs';
const dataText=readFileSync('data/private/cv.master.json','utf8');const publicText=readFileSync('data/public/cv.master.example.json','utf8');const data=JSON.parse(dataText);
test('correct employers, periods and mandatory stations',()=>{const must={"freelance-digital-marketing-media":"03/2026 – heute","kunz-kunath-marketing-mediamatiker":"10/2021 – 02/2026","rekrutenschule-triage-fuehrungsdienst":"11/2022 – 03/2023","mediamatiker-ausbildung-army-bict":"08/2017 – 08/2021","schachfestival-livestream-event":"Juli 2019 / 2020"};for(const [id,period] of Object.entries(must)){const e=data.experiences.find(x=>x.id===id);assert.ok(e,id);assert.equal(e.period,period)}assert.equal(data.experiences.find(e=>e.id==='kunz-kunath-marketing-mediamatiker').employer,'Kunz Kunath AG');assert.ok(!data.experiences.some(e=>/FORS/i.test(e.employer)))});
test('freelance location uses sourced Neukaledonien wording and never France',()=>{assert.equal(dataText.includes('Frankreich'),false);const e=data.experiences.find(x=>x.id==='freelance-digital-marketing-media');assert.ok(e.employer.includes('Neukaledonien'));assert.ok(e.employer.includes('ab 06/2026 in Bern'));assert.equal(e.location,'Neukaledonien / Bern')});
test('Kunz Kunath contains sourced Onlineshop content bullet and no monitoring wording',()=>{const flat=JSON.stringify(data);assert.ok(flat.includes('Onlineshop-Management inkl. Content-, Struktur- und Produktpflege'));assert.equal(flat.includes('Onlinekampagnen inkl. Monitoring und Erfolgskontrolle'),false)});
test('workload text is exact',()=>{assert.equal(data.workload.text,'60–100 % flexibel nach Absprache')});
test('languages and references are complete and real',()=>{assert.deepEqual(data.languages.map(l=>l.name),['Deutsch','Englisch','Französisch','Polnisch']);for(const [name,level] of [['Deutsch','C2'],['Englisch','C1'],['Französisch','B1'],['Polnisch','C2']])assert.ok(data.languages.find(l=>l.name===name&&l.level===level));assert.deepEqual(data.references.map(r=>r.name),['Peter Stadelmann','Peter Wyss']);assert.ok(data.references.every(r=>/^\+\d+/.test(r.phone)));const wyss=data.references.find(r=>r.name==='Peter Wyss');assert.equal(wyss.phone,'+41 58 489 20 03');assert.equal('manualVerificationRequired' in wyss,false);assert.equal(dataText.includes('+51 58 489 20 03'),false);assert.equal(publicText.includes('+51 58 489 20 03'),false)});
test('schema-like validation requires sourced ids',()=>{for(const s of data.skillSections)for(const i of s.items){assert.ok(i.id);assert.ok(i.tags.length);assert.ok(i.evidenceLevel);assert.ok(i.sources.length)}for(const e of data.experiences)for(const b of e.bullets){assert.ok(b.id);assert.ok(b.sources.length)}});
test('variants alter selection and order',()=>{const general=JSON.parse(readFileSync('data/public/variants/general.json','utf8'));const admin=JSON.parse(readFileSync('data/public/variants/administration-gever.json','utf8'));assert.notDeepEqual(general.skillSectionOrder,admin.skillSectionOrder);assert.ok(admin.hiddenSkillSections.includes('content-media'));assert.notDeepEqual(general.toolOrder.slice(0,3),admin.toolOrder.slice(0,3));assert.equal(general.maxBulletsPerExperience,7);assert.ok(general.selectedBulletIds.includes('bullet-freelance-french'));assert.ok(general.selectedBulletIds.includes('bullet-freelance-self-organization'))});
test('workflow avoids npm ci/cache npm without lockfile and uses Node 22',()=>{const wf=readFileSync('.github/workflows/render-cv.yml','utf8');assert.equal(wf.includes('npm ci'),false);assert.equal(wf.includes('cache: npm'),false);assert.equal(wf.includes('push:'),false);assert.ok(wf.includes('node-version: 22'));assert.ok(wf.includes('npm install --no-audit --no-fund'))});
test('validate passes and TypeScript build fails on errors',()=>{assert.equal(spawnSync(process.execPath,['scripts/validate.mjs']).status,0);const bad=spawnSync('sh',['-c','tmp=$(mktemp --suffix=.ts); echo "const x: string = 1" > $tmp; tsc --noEmit --strict $tmp >/dev/null 2>&1; s=$?; rm $tmp; exit $s']);assert.notEqual(bad.status,0)});

test('optional and supplementary content is verified and variant-bound',()=>{assert.ok(data.supplementaryIndicators?.tools?.enabled);const optional=data.experiences.flatMap(e=>(e.optionalBullets||[]).map(b=>({...b,experienceId:e.id})));assert.ok(optional.length>=4);for(const b of optional){assert.ok(b.id.startsWith('optional-'));assert.ok(b.text);assert.ok(b.shortText);assert.ok(b.tags.length);assert.ok(b.evidenceLevel);assert.ok(b.sources.length);assert.ok(b.variantRelevance.length);assert.ok(Number.isInteger(b.fillPriority));assert.ok(b.preferredMaxChars>0);assert.ok(['verified','defensible_inference','inferred_review_required'].includes(b.status));assert.ok(Array.isArray(b.atsSynonyms))}const training=data.experiences.find(e=>e.id==='mediamatiker-ausbildung-army-bict');assert.ok(training.optionalBullets.some(b=>/Web|digitale Medien|Dokumentation|Projektarbeit/.test(b.text)));const event=data.experiences.find(e=>e.id==='schachfestival-livestream-event');assert.ok(event.optionalBullets.some(b=>/Livestreaming|Eventorganisation|Veranstaltungsbetrieb/.test(b.text))) });


test('page.evaluate transfers one serializable payload object',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('page.evaluate(({ bgExists, variantMeta }) =>'));assert.ok(src.includes('bgExists: backgroundFileExists'));assert.equal(src.includes('}, backgroundFileExists, {'),false)});

test('tool pool includes only sourced tool records with visibility metadata',()=>{assert.ok(data.tools.length>11);for(const tool of data.tools){assert.ok(tool.id.startsWith('tool-'));assert.ok(tool.name);assert.ok(tool.tags.length);assert.ok(tool.evidenceLevel);assert.ok(tool.sources.length);assert.equal(typeof tool.surfaceAutomatically,'boolean');assert.ok(Array.isArray(tool.allowedVariants));assert.ok(Number.isInteger(tool.priority));assert.ok(tool.category);assert.ok(Array.isArray(tool.atsSynonyms));assert.ok(['verified','defensible_inference','inferred_review_required'].includes(tool.status))}assert.ok(data.tools.find(t=>t.id==='tool-adobe-indesign'&&t.surfaceAutomatically===false));assert.ok(data.tools.find(t=>t.id==='tool-adobe-photoshop'&&t.surfaceAutomatically===false))});


test('fill gap uses visible experience content bottom instead of flex container bottom',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('getExperienceContentBottom'));assert.ok(src.includes("#experience-list .experience:not([hidden])"));assert.equal(src.includes('bottomGrid.top - experienceList.bottom'),false)});


test('adaptive fill uses preferred and max counts instead of hard optionalBulletLimit',()=>{for(const name of ['general','communication-content','administration-gever','cms-web-process']){const v=JSON.parse(readFileSync(`data/public/variants/${name}.json`,'utf8'));assert.equal('optionalBulletLimit' in v.fill,false);assert.ok(v.fill.preferredOptionalBulletCount>=0);assert.ok(v.fill.maxOptionalBullets>=v.fill.preferredOptionalBulletCount)}});

test('administration variant includes ATS-friendly administrative source blocks',()=>{const admin=JSON.parse(readFileSync('data/public/variants/administration-gever.json','utf8'));for(const id of ['bullet-rs-acta-nova','bullet-rs-quality','bullet-rs-doc-management','bullet-rs-coordination','bullet-kunz-process-handover'])assert.ok(admin.selectedBulletIds.includes(id));const flat=JSON.stringify(data);for(const term of ['Digitale Geschäftsvorgangsbearbeitung','Dokumentenmanagement','Qualitätsprüfung','formale Kontrolle','Prozessdokumentation','Wissenssicherung'])assert.ok(flat.includes(term),term)});


test('ATS normalization is case-insensitive and robust against PDF line breaks',()=>{assert.equal(normalizeAtsText('ADAM DOLINSKY'),normalizeAtsText('Adam Dolinsky'));assert.equal(normalizeAtsText('Digital Marketing · Web · Content · KI-\ngestützte Prozesse'),normalizeAtsText('Digital Marketing · Web · Content · KI-gestützte Prozesse'));assert.equal(normalizeAtsText('MS Office'),normalizeAtsText('MS Office'));assert.equal(normalizeAtsText('Kunz   Kunath AG'),normalizeAtsText('Kunz Kunath AG'))});

test('ATS normalization does not fuzzy-match absent terms',()=>{const pdfText=normalizeAtsText('ADAM DOLINSKY Digital Marketing · Web · Content · KI-\ngestützte Prozesse MS Office Kunz   Kunath AG');assert.equal(pdfText.includes(normalizeAtsText('Nicht vorhandener Begriff')),false)});


test('PDF.js hasEOL item joining preserves hyphenated line breaks for ATS matching',()=>{const items=[{str:'Digital Marketing · Web · Content · KI-',transform:[1,0,0,10,10,100],width:120,height:10,hasEOL:true},{str:'gestützte Prozesse',transform:[1,0,0,10,10,88],width:80,height:10,hasEOL:false}];const extracted=joinPdfTextItems(items);assert.equal(extracted,'Digital Marketing · Web · Content · KI-\ngestützte Prozesse');assert.equal(normalizeAtsText(extracted),normalizeAtsText('Digital Marketing · Web · Content · KI-gestützte Prozesse'))});

test('PDF.js item joining does not collapse legitimate hyphen-space wording',()=>{const items=[{str:'Newsletter-Konzeption und Umsetzung (Print- und E-Mail)',hasEOL:false}];const extracted=joinPdfTextItems(items);assert.equal(extracted,'Newsletter-Konzeption und Umsetzung (Print- und E-Mail)');assert.equal(normalizeAtsText(extracted),normalizeAtsText('Newsletter-Konzeption und Umsetzung (Print- und E-Mail)'));assert.equal(normalizeAtsText(extracted).includes('print-und e-mail'),false)});


test('each variant has at least fourteen sourced visible tools',()=>{const master=new Map(data.tools.map(t=>[t.id,t]));for(const name of ['general','communication-content','administration-gever','cms-web-process']){const v=JSON.parse(readFileSync(`data/public/variants/${name}.json`,'utf8'));const ids=v.toolOrder.slice(0,v.maxTools);assert.ok(ids.length>=14,`${name} tool count`);assert.equal(new Set(ids).size,ids.length,`${name} unique tools`);for(const id of ids){const tool=master.get(id);assert.ok(tool,`${id} in master`);assert.ok(tool.sources?.length,`${id} sourced`);assert.notEqual(tool.status,'inferred_review_required',`${id} not review-only`)}}});

test('visible experience bullet fallback content is source-backed and safe',()=>{const rs=data.experiences.find(e=>e.id==='rekrutenschule-triage-fuehrungsdienst');for(const id of ['bullet-rs-admin-support-summary','bullet-rs-digital-information-summary']){const bullet=rs.bullets.find(b=>b.id===id);assert.ok(bullet,id);assert.ok(['verified','defensible_inference'].includes(bullet.status));assert.ok(bullet.sources?.length);assert.ok(bullet.sourceIds?.length);assert.ok(bullet.inferenceRationale)}});

test('PDF.js geometry-aware v2 joining repairs adjacent word fragments even with misleading hasEOL',()=>{const cases=[[[{str:'Pazif',transform:[1,0,0,10,10,100],width:18,height:10,hasEOL:true},{str:'ikregion',transform:[1,0,0,10,28.2,100],width:30,height:10,hasEOL:false}],'Pazifikregion'],[[{str:'Schachf',transform:[1,0,0,10,10,100],width:26,height:10,hasEOL:true},{str:'estival',transform:[1,0,0,10,36.1,100],width:24,height:10,hasEOL:false}],'Schachfestival'],[[{str:'Adobe Prem',transform:[1,0,0,10,10,100],width:45,height:10,hasEOL:true},{str:'iere Pro',transform:[1,0,0,10,55.2,100],width:30,height:10,hasEOL:false}],'Adobe Premiere Pro'],[[{str:'phpMy',transform:[1,0,0,10,10,100],width:25,height:10,hasEOL:false},{str:'Admin',transform:[1,0,0,10,35.1,100],width:24,height:10,hasEOL:false}],'phpMyAdmin'],[[{str:'Off',transform:[1,0,0,10,10,100],width:14,height:10,hasEOL:true},{str:'ice 365',transform:[1,0,0,10,24.1,100],width:34,height:10,hasEOL:false}],'Office 365'],[[{str:'Me',transform:[1,0,0,10,10,100],width:10,height:10,hasEOL:true},{str:'diamatiker',transform:[1,0,0,10,20.1,100],width:42,height:10,hasEOL:false}],'Mediamatiker']];for(const [items,expected] of cases){const stats={};assert.equal(joinPdfTextItems(items,stats),expected);assert.ok(stats.fragmentJoinCount>0)}});

test('PDF.js geometry-aware joining preserves real word gaps',()=>{let totalSpaces=0;const cases=[[[{str:'Kunz',transform:[1,0,0,1,10,100],width:20,height:10,hasEOL:false},{str:'Kunath',transform:[1,0,0,1,34,100],width:30,height:10,hasEOL:false}],'Kunz Kunath'],[[{str:'Microsoft',transform:[1,0,0,1,10,100],width:42,height:10,hasEOL:false},{str:'Office',transform:[1,0,0,1,56,100],width:24,height:10,hasEOL:false}],'Microsoft Office'],[[{str:'Adobe',transform:[1,0,0,1,10,100],width:25,height:10,hasEOL:false},{str:'InDesign',transform:[1,0,0,1,39,100],width:36,height:10,hasEOL:false}],'Adobe InDesign'],[[{str:'Digital',transform:[1,0,0,10,10,100],width:30,height:10,hasEOL:false},{str:'Marketing',transform:[1,0,0,10,45,100],width:42,height:10,hasEOL:false}],'Digital Marketing']];for(const [items,expected] of cases){const stats={};assert.equal(joinPdfTextItems(items,stats),expected);totalSpaces+=stats.insertedSpaceCount}assert.ok(totalSpaces>=cases.length)});

test('PDF.js geometry-aware joining preserves legitimate hyphen wording',()=>{for(const text of ['Print- und E-Mail','Foto- und Videoproduktion','Web- und IT-Partner','deutsch- und französischsprachig'])assert.equal(joinPdfTextItems([{str:text,transform:[1,0,0,1,10,100],width:80,height:10,hasEOL:false}]),text)});

test('summary candidates exist for every base variant',()=>{assert.equal(data.summary.candidates['cms-web-process'][0].id,'cms-extended');assert.equal(data.summary.candidates['cms-web-process'][1].id,'cms-expanded');for(const key of ['default','communication-content','administration-gever','cms-web-process']){const candidates=data.summary.candidates[key];assert.ok(Array.isArray(candidates));assert.ok(candidates.length>=3);for(const c of candidates){assert.ok(c.id);assert.ok(c.text);assert.ok(c.evidenceIds.length);assert.ok(c.atsTerms.length);assert.equal(c.text.includes('<br>'),false)}}});


test('rekrutenschule overlap note is removed from production data',()=>{const forbidden='Während Anstellung im Zeitraum bei Kunz Kunath AG';assert.equal(JSON.stringify(data).includes(forbidden),false);const example=JSON.parse(readFileSync('data/public/cv.master.example.json','utf8'));assert.equal(JSON.stringify(example).includes(forbidden),false)});

test('workflow installs Poppler and uploads raw and layout Poppler text artifacts',()=>{const wf=readFileSync('.github/workflows/render-cv.yml','utf8');assert.ok(wf.includes('Install PDF text tools'));assert.ok(wf.includes('poppler-utils'));assert.ok(wf.includes('dist/text-*-poppler-raw.txt'));assert.ok(wf.includes('dist/text-*-poppler-layout.txt'))});

test('round 17 visual review is aggregated after all renders',()=>{const render=readFileSync('scripts/render.mjs','utf8');const renderAll=readFileSync('scripts/render-all.mjs','utf8');assert.equal(render.includes('visual-review-round-17.json'),false);assert.ok(renderAll.includes('visual-review-round-17.json'));assert.ok(renderAll.includes('overallSuccess'));assert.ok(renderAll.includes('render-report-${variant}.json'))});

test('Figtree text uses natural spacing and real local font faces',()=>{const css=readFileSync('src/styles/cv.css','utf8');const pkg=JSON.parse(readFileSync('package.json','utf8'));assert.ok(pkg.dependencies['@fontsource/figtree']);assert.equal('@fontsource/poppins' in pkg.dependencies,false);for(const file of ['figtree-latin-400-normal.woff2','figtree-latin-500-normal.woff2','figtree-latin-600-normal.woff2','figtree-latin-700-normal.woff2','figtree-latin-400-italic.woff2','figtree-latin-500-italic.woff2','figtree-latin-600-italic.woff2','figtree-latin-700-italic.woff2'])assert.ok(css.includes(file),file);assert.ok(css.includes('font-variant-ligatures:none'));assert.ok(css.includes('font-kerning:normal'));assert.ok(css.includes('font-feature-settings:normal'));assert.ok(css.includes('font-synthesis:none'));assert.ok(css.includes('letter-spacing:normal'));assert.ok(css.includes('word-spacing:normal'));assert.equal(css.includes('font-kerning:none'),false);assert.equal(css.includes('"kern" 0'),false);assert.equal(css.includes('Poppins'),false)});

test('render failures expose render stage and full stack',()=>{const src=readFileSync('scripts/render.mjs','utf8');for(const stage of ['startup','playwright-import','browser-launch','preview-navigation','font-loading','summary-selection','initial-layout-metrics','adaptive-fill','interaction-checks','required-term-collection','pdf-export','page-one-screenshot','page-two-screenshot','browser-close'])assert.ok(src.includes(stage),stage);assert.ok(src.includes('Render failed at stage: ${renderStage}'));assert.ok(src.includes('error?.stack || error'));assert.equal(src.includes('Production render requires Playwright/Chromium:'),false)});

test('Figtree computed style diagnostics are null-safe',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes("const cssString = (value) => typeof value === 'string' ? value : ''"));assert.ok(src.includes('function readComputedSample(selector)'));assert.ok(src.includes('found: false'));assert.ok(src.includes('Figtree diagnostic selector missing'));assert.equal(src.includes('sample.fontFeatureSettings.includes('),false);assert.ok(src.includes('figtreeComputedSamples'));assert.ok(src.includes('skillHeadingSamples'))});

test('visual review cannot pass when reports are missing',()=>{const src=readFileSync('scripts/render-all.mjs','utf8');assert.ok(src.includes('reportsPresent'));assert.ok(src.includes('artifactCompleteness'));assert.ok(src.includes('missingFiles'));assert.ok(src.includes('Boolean(report)'));assert.ok(src.includes('selectionSucceeded === true'));assert.equal(src.includes("reports[variant]?.summary?.actualLines === reports[variant]?.summary?.targetLines"),false);assert.ok(src.includes('Production render failed before PDF/report generation'));assert.ok(src.includes('allReportsPresent'));assert.ok(src.includes('artifactCompleteness.complete'))});

test('render catch persists structured render-failure diagnostics and closes browser safely',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('function writeRenderFailure(error)'));assert.ok(src.includes('dist/render-failure-${variantId}.json'));for(const key of ['variant: variantId','renderStage','errorName','errorMessage','errorStack','nodeVersion: process.version','platform: process.platform','timestamp: new Date().toISOString()'])assert.ok(src.includes(key),key);assert.ok(src.includes('let browser = null'));assert.ok(src.includes('async function closeBrowserIfOpen()'));assert.ok(src.includes('finally {'));assert.ok(src.includes('await closeBrowserIfOpen()'));assert.ok(src.includes('Browser close failed:'));assert.ok(src.includes('failureRenderStage'))});

test('render-all captures variant logs and failure files for visual review',()=>{const src=readFileSync('scripts/render-all.mjs','utf8');assert.ok(src.includes("encoding: 'utf8'"));assert.ok(src.includes('process.stdout.write(stdout)'));assert.ok(src.includes('process.stderr.write(stderr)'));assert.ok(src.includes('dist/render-log-${variant}.txt'));assert.ok(src.includes("'STDOUT'"));assert.ok(src.includes("'STDERR'"));assert.ok(src.includes('renderFailures'));assert.ok(src.includes('dist/render-failure-${variant}.json'));assert.ok(src.includes('InvalidRenderFailureJson'));assert.ok(src.includes('present: false'));assert.ok(src.includes('diagnosticArtifacts'));assert.ok(src.includes('renderFailureCount'));assert.ok(src.includes('renderLogCount'))});

test('workflow uploads render failure diagnostics and logs',()=>{const wf=readFileSync('.github/workflows/render-cv.yml','utf8');assert.ok(wf.includes('dist/render-failure-*.json'));assert.ok(wf.includes('dist/render-log-*.txt'));assert.ok(wf.includes('if: always()'))});



test('semantic ATS required terms prefer data-ats-text and deduplicate language terms',()=>{const src=readFileSync('scripts/render.mjs','utf8');for(const term of ['Deutsch C2','Englisch C1','Französisch B1','Polnisch C2'])assert.ok(src.includes('${language.name} ${language.level}')||src.includes(term));assert.ok(src.includes('data-ats-text'));assert.ok(src.includes("element.getAttribute('data-ats-text')"));assert.ok(src.includes('explicit || element.innerText || element.textContent'));assert.ok(src.includes('new Set(metrics.ats.requiredTerms)'))});

test('tools supplementary text is exact and free of hidden spacing characters',()=>{const toolsMoreText='+ weitere mediamatikbezogene Tools und Systeme';assert.equal(data.supplementaryIndicators.tools.text,toolsMoreText);for(const ch of ['\u00A0','\u2009','\u200B','\u202F','\u2060','\u00AD'])assert.equal(data.supplementaryIndicators.tools.text.includes(ch),false,ch);assert.equal(/ {2,}/.test(data.supplementaryIndicators.tools.text),false);const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('class="supplementary tools-more"'));assert.ok(src.includes('data-ats-text'))});

test('Poppler raw is primary and layout/PDF.js are diagnostics',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes("mode === 'raw' ? '-raw' : '-layout'"));assert.ok(src.includes('popplerRaw'));assert.ok(src.includes('popplerLayout'));assert.ok(src.includes("primaryExtractor: 'poppler-raw'"));assert.ok(src.includes("role: 'primary-ats-extractor'"));assert.ok(src.includes("role: 'layout-diagnostic'"));assert.ok(src.includes("role: 'secondary-diagnostic'"));assert.ok(src.includes('primaryAtsSuccess'));assert.equal(src.includes('extractors?.poppler?.success'),false)});

test('metrics initializes ATS shell before required term collection',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('ats: { hiddenTextDetected: false, requiredTerms: [] }'));assert.ok(src.includes('metrics.ats ??= { hiddenTextDetected: false, requiredTerms: [] }'));assert.ok(src.includes('if (!Array.isArray(metrics.ats.requiredTerms)) metrics.ats.requiredTerms = []'));assert.ok(src.includes("element.getAttribute('data-ats-text')"));assert.ok(src.includes('element.innerText'));assert.ok(src.includes('metrics.ats.requiredTerms = [...new Set(metrics.ats.requiredTerms)]'));assert.equal(src.includes('Cannot set properties of undefined'),false)});

test('final ATS report receives a safe requiredTerms array and handles missing ATS shell',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('const requiredTerms = Array.isArray(metrics.ats?.requiredTerms) ? metrics.ats.requiredTerms : []'));assert.ok(src.includes('metrics, requiredTerms'));assert.ok(src.includes('hiddenTextDetected: Boolean(metrics?.ats?.hiddenTextDetected)'));assert.equal(src.includes('buildAtsReport(`dist/Lebenslauf_Adam-Dolinsky_${variantId}.pdf`, metrics, metrics.ats.requiredTerms)'),false)});

test('single-variant render removes stale failure and production artifacts before rerendering',()=>{const src=readFileSync('scripts/render.mjs','utf8');assert.ok(src.includes('const staleFiles = ['));for(const item of ['dist/render-failure-${variantId}.json','dist/render-report-${variantId}.json','dist/Lebenslauf_Adam-Dolinsky_${variantId}.pdf','dist/cv-${variantId}-page-1.png','dist/cv-${variantId}-page-2.png','dist/text-${variantId}-poppler.txt','dist/text-${variantId}-poppler-raw.txt','dist/text-${variantId}-poppler-layout.txt'])assert.ok(src.includes(item),item);assert.ok(src.includes('if (existsSync(file)) unlinkSync(file)'));assert.ok(src.includes('unlinkSync'))});
