import test from 'node:test';import assert from 'node:assert/strict';import {existsSync,readFileSync} from 'node:fs';
const variants=['general','communication-content','administration-gever','cms-web-process'];
const report=v=>JSON.parse(readFileSync(`dist/render-report-${v}.json`,'utf8'));
const isWhite=c=>c==='rgb(255, 255, 255)'||c==='white'; const isBlue=c=>/rgb\((14|21), (63|81), (125|159)\)/.test(c)||/#15519f|#0e3f7d/i.test(c);

test('all render reports are successful with two pages and no layout problems',()=>{for(const v of variants){const r=report(v);assert.equal(r.success,true,v);assert.equal(r.renderer,'playwright',v);assert.equal(r.pageCount,2,v);assert.deepEqual(r.overflows,[],`${v} overflows`);assert.deepEqual(r.collisions,[],`${v} collisions`);assert.deepEqual(r.warnings,[],`${v} warnings`);assert.equal(r.assets?.profile?.loaded,true,`${v} profile image`);assert.equal(r.assets?.background?.computed,true,`${v} bg computed`);assert.equal(r.assets?.background?.reachable,true,`${v} bg reachable`);assert.equal(r.assets?.background?.rendered,true,`${v} bg rendered`);assert.equal(r.assets?.background?.coversFullPage,true,`${v} bg full page`);assert.equal(r.assets?.background?.bottomZoneNotGray,true,`${v} no gray lower zone`);assert.equal(r.assets?.background?.size,'cover',`${v} bg size`);assert.equal(r.assets?.background?.repeat,'no-repeat',`${v} bg repeat`);assert.equal(r.assets?.background?.topLeftLaptopExpected,true,`${v} laptop crop`);assert.ok(r.fonts?.heading&&r.fonts?.body&&r.fonts?.slab,`${v} fonts`);assert.equal(r.fonts.slabLoaded,true,`${v} Roboto Slab loaded`);assert.match(r.fonts.slab,/Roboto Slab/i,`${v} slab applied`);assert.equal(/Times New Roman/i.test(`${r.fonts.heading} ${r.fonts.body} ${r.fonts.slab}`),false,`${v} no times`);assert.ok(r.links.length>=3,`${v} links`)}});

test('artifacts exist for every variant',()=>{for(const v of variants){for(const p of [`dist/Lebenslauf_Adam-Dolinsky_${v}.pdf`,`dist/cv-${v}-page-1.png`,`dist/cv-${v}-page-2.png`,`dist/cv-${v}-preview.html`,`dist/render-report-${v}.json`])assert.ok(existsSync(p),`${p} missing`)}});

test('general preview does not duplicate freelance location line',()=>{const html=readFileSync('dist/cv-general-preview.html','utf8');const line='bis 05/2026 Pazifikregion (Neukaledonien), ab 06/2026 in Bern';assert.equal(html.includes(line),true);assert.equal(html.includes(`${line}, Neukaledonien / Bern`),false)});

test('button normal, hover and focus-visible states are deterministic',()=>{const r=report('general');assert.equal(isWhite(r.buttonStates.normal.backgroundColor),true,'normal bg white');assert.equal(isBlue(r.buttonStates.normal.color),true,'normal text blue');assert.equal(isWhite(r.buttonStates.normal.borderColor),true,'normal border white');assert.equal(isBlue(r.buttonStates.hover.backgroundColor),true,'hover bg blue');assert.equal(isWhite(r.buttonStates.hover.color),true,'hover text white');assert.equal(isWhite(r.buttonStates.hover.borderColor),true,'hover border white');assert.notEqual(r.buttonStates.normal.backgroundColor,r.buttonStates.hover.backgroundColor);assert.notEqual(r.buttonStates.normal.color,r.buttonStates.hover.color);assert.equal(r.buttonStates.focus.isFocusVisible,true);assert.equal(isBlue(r.buttonStates.focus.backgroundColor),true,'focus bg blue');assert.equal(isWhite(r.buttonStates.focus.color),true,'focus text white')});

test('email contact link is not rendered as a pill button and final artifacts are unfocused',()=>{const r=report('general');assert.equal(r.emailState.display,'inline');assert.equal(r.emailState.borderWidth,'0px');assert.equal(r.emailState.borderRadius,'0px');assert.equal(r.emailState.boxShadow,'none');assert.equal(r.emailState.outlineStyle,'none');assert.equal(r.finalInteractiveState.linkButtonFocused,false);assert.equal(r.finalInteractiveState.linkButtonHovered,false);assert.equal(r.finalInteractiveState.emailFocused,false)});

test('supplementary indicators only describe omitted verified content',()=>{for(const v of variants){const r=report(v);assert.ok(r.supplementary);for(const item of r.supplementary.items){if(item.type==='tools')assert.ok(item.omittedToolIds.length>0);if(item.type==='experience')assert.ok(item.omittedBulletIds.length>0)}assert.ok(r.fill.baselineGapPx>=r.fill.finalGapPx);assert.ok(Array.isArray(r.fill.consideredOptionalBulletIds));assert.ok(Array.isArray(r.fill.acceptedOptionalBulletIds));assert.ok(Array.isArray(r.fill.rejectedOptionalBulletIds));assert.ok(r.fill.optionalBulletsUsed<=r.fill.optionalBulletLimit);assert.ok(r.fill.minRemainingSpaceMm>=5);const expHints=r.supplementary.items.filter(i=>i.type==='experience');assert.ok(expHints.length<=r.supplementary.maxExperienceIndicators);if(r.supplementary.toolsIndicator)assert.ok(r.supplementary.toolsIndicator.omittedToolIds.length>0)}});
